import {test,expect} from 'bun:test';
import {nextAction,setMode,approveGate,enforceMutation,enforceGate,waveGate} from '../src/controller';
import type {Mission,Snapshot,PolicyContext} from '../src/types';
export function fixture(): Mission {return {version:1,id:'freeform-test',source:{kind:'freeform',id:'test',title:'test',body:'test',comments:'',extra:''},workspace:{key:'key',cwd:'/tmp',delivery:'local'},epicId:'epic',scopes:{a:['a.ts'],b:['b.ts']},phase:'execute',evidence:{},mode:'auto',keep:false,reviewRequested:false,workers:[],reviews:[],repairLinks:{},round:1,createdAt:'now',updatedAt:'now'};}
const ready:Snapshot={beads:[{id:'a',title:'a',status:'open',children:[],ready:true,category:'ready'},{id:'b',title:'b',status:'open',children:[],ready:true,category:'ready'}],leaves:[],ready:['a','b'],closed:0,active:0,blocked:0,fetchedAt:Date.now()};ready.leaves=ready.beads;
const policy:PolicyContext={resumeHold:false,owned:true,nativePlan:false,fresh:true,maxWorkers:2};
const closedBeads=ready.beads.map(bead=>({...bead,status:'closed',category:'closed' as const,ready:false}));
const closed:Snapshot={...ready,beads:closedBeads,leaves:closedBeads,ready:[],closed:2};
test('resume hold survives mode switch and Force request',()=>{const m=fixture();setMode(m,'force');expect(m.reviewRequested).toBe(true);expect(nextAction(m,ready,{...policy,resumeHold:true}).kind).toBe('hold');expect(()=>enforceMutation(m,{...policy,resumeHold:true})).toThrow('Resumed inspection');});
test('force plus pause retains review but gates wave',()=>{const m=fixture();setMode(m,'force');setMode(m,'pause');const action=nextAction(m,ready,policy);expect(m.reviewRequested).toBe(true);expect(action.gate?.kind).toBe('wave');m.gate=action.gate;approveGate(m,m.gate!.token);expect(nextAction(m,ready,policy).kind).toBe('dispatch');});
test('changed scope invalidates approval',()=>{const m=fixture();m.mode='pause';m.gate=waveGate(m,['a','b'],ready);approveGate(m,m.gate.token);m.scopes.a=['changed.ts'];expect(nextAction(m,ready,policy).kind).toBe('hold');expect(()=>enforceGate(m,waveGate(m,['a','b'],ready))).toThrow('Approval required');});
test('Pause mid wave neither cancels nor backfills',()=>{const m=fixture();m.workers=[{beadId:'a',attempt:'1',cwd:'/tmp',files:['a.ts'],state:'running',assignment:'a'}];setMode(m,'pause');const action=nextAction(m,ready,policy);expect(action.kind).toBe('hold');expect(action.ids).toBeUndefined();expect(m.workers[0]?.state).toBe('running');});
test('stale reads never dispatch and plan blocks all mutations',()=>{const m=fixture();expect(nextAction(m,{...ready,error:'bd failed'},policy).kind).toBe('hold');expect(()=>enforceMutation(m,{...policy,nativePlan:true})).toThrow('native plan');});
test('delivery without requested review is not complete',()=>{const m=fixture();m.evidence.verify={outcome:'passed',revision:'rev',detail:'actual',at:'now'};m.evidence.deliver={outcome:'passed',detail:'local',at:'now'};expect(nextAction(m,closed,policy).kind).toBe('hold');m.reviewRequested=true;expect(nextAction(m,closed,policy).kind).toBe('review');m.reviews=[{round:1,revision:'rev',model:'model',summary:'clean',findings:[],at:'now'}];expect(nextAction(m,closed,policy).kind).toBe('complete');});
test('failed review holds until explicitly retried or a new revision is verified',()=>{const m=fixture();m.reviewRequested=true;m.evidence.verify={outcome:'passed',revision:'rev',detail:'Node assertions passed',at:'now'};m.evidence.deliver={outcome:'passed',revision:'rev',detail:'local',at:'now'};m.evidence.review={outcome:'failed',revision:'rev',detail:'Malformed reviewer JSON',at:'now'};expect(nextAction(m,closed,policy).kind).toBe('hold');delete m.evidence.review;expect(nextAction(m,closed,policy).kind).toBe('review');});
test('empty graph cannot advance to verification or delivery',()=>{const m=fixture();expect(nextAction(m,{...ready,beads:[],leaves:[],ready:[]},policy).kind).toBe('hold');});
test('Pause independently gates review entry and repair acceptance',()=>{const m=fixture();m.mode='pause';m.reviewRequested=true;m.evidence.verify={outcome:'passed',revision:'rev',detail:'Node assertions passed',at:'now'};m.evidence.deliver={outcome:'passed',revision:'rev',detail:'local',at:'now'};m.gate=nextAction(m,closed,policy).gate;expect(m.gate?.kind).toBe('review');approveGate(m,m.gate!.token);expect(nextAction(m,closed,policy).kind).toBe('review');m.reviews=[{round:1,revision:'rev',model:'independent',summary:'Defect',findings:[{id:'R1',severity:'high',path:'a.ts',line:1,title:'Boundary defect',body:'Boundary defect'}],at:'now'}];m.gate=nextAction(m,closed,policy).gate;expect(m.gate?.kind).toBe('repairs');approveGate(m,m.gate!.token);expect(nextAction(m,closed,policy).kind).toBe('repairs');});
